### ISSUE TITLE
When saving a CaseStatus, a validation error occurs if the parent Case is missing a title on one of the languages

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Cases#22]
POST `{{cases}}{{environment}}/case-statuses`

Response:
```
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "detail": "case.title[fr]: This value should not be blank.",
    "violations": [
        {
            "propertyPath": "case.title[fr]",
            "message": "This value should not be blank."
        }
    ]
}
```

**Comment by marioprudhomme** [comment]
The problem is being caused by submitting partial translations (for example: no french title, but french data object). The case is saved in an invalid state, despite the api accepting it. Then later on passes thru the validation via POST /case-statuses

Validation annotations needs to be revised in order to validate at the entity level all required translate fields, not just at the attribute level.

**Comment by marioprudhomme** [comment]
Done. 93b1ff1faca434f0d7c3c546e5663a6b25f572a9
